language: csharp
sudo: required
mono: none
dotnet: 2.2.101
addons:
  apt:
    install:
    - dpkg
env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
script:
  - dotnet build Flagger.csproj
